### ISSUE TITLE
Should send AIVDO messages instead of AIVDM

### ISSUE THREAD

**Issue by hkapanen** [SignalK/aisreporter#18]
"AIVDM packets are reports from other ships and AIVDO packets are reports from your own ship." as per http://catb.org/gpsd/AIVDM.html#_introduction.

**Comment by webmasterkai** [comment]
It's usually better to send AIVDM to an online service. In some cases AIVDO is completely ignored by the iAIS providers/aggregators. Because the iAIS service is often listening to any/all traffic on a UDP port I have seen many of them implement a very basic whitelist to prevent the processing of non-AIS messages. Sometimes that "whitelist" is simply a `if (message.startsWith('!AIVDM')`. Other times multiple AIS inputs are aggregated on the provider side and retransmitted to other entities. Since the checksum changes depending on AIVDO or AIVDM it's less work on the provider server to have everything in AIVDM format so checksums don't need to be recalculated when switching AIVDO to AIVDM.

On the onboard NMEA 0183 network it is appropriate and accurate to use AIVDO for own ship. But in the case of sending it to the internet using AIVDM is acceptable and sometimes/often preferred.

**Comment by hkapanen** [comment]
Ah, ok, see it now. Thanks!
